networks:
  inception:
    name: inception
    driver: bridge

# Services to run ( containers )
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env

# Create volumes ( VOLUMES_PATH exported by Makefile )
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/wordpress
